version: '3'

services:
  api:
    image: php:7-apache
    volumes:
      - ./api/:/var/www/html:ro
    ports:
      - 8888:80
  app:
    image: php:7-apache
    environment:
      - API_LOCATION=http://api/dictAPI.php/
    volumes:
      - ./src:/var/www/html:ro
    ports:
      - 80:80
