version: '3'

services:
  api:
    image: php:7-apache
    volumes:
      - ./api/:/var/www/html:ro
    ports:
      - 8888:80
  app:
    build:
      context: ./
      dockerfile: DockerfileApp
    volumes:
      - ./src:/var/www/html:ro
    ports:
      - 443:443
